<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add fixed tax')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form class="api-form form-horizontal" data-clone-field="[data-clone=add-fixed-tax]" data-clone-target="[data-table-body='fixed-tax']" action="/<?= $this->module_name ?>/add-fixed-tax.json" method="POST" name="form-add-fixed-tax" role="form" >
                        <!-- Form Name -->                        
                        <input type="hidden" name="company_id" value="<?= $this->companyModel->getCurrentPeopleCompany() ? $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>">
                        <input name="method" value="POST" type="hidden">
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-fixed-tax" for="input-add-fixed-tax"><?= $this->translate('Tax Name') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-fixed-tax" name="fixed-tax" required>                                    
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-price" for="input-add-tax-price"><?= $this->translate('Price') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-tax-price" name="tax-price" data-mask="({prefix: '<?= $this->translate('corrency_symbol')?> ',clearIncomplete: true,digits: 3,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})" required>
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-minimum" for="input-add-tax-minimum"><?= $this->translate('Minimum Tax') ?>: </label>
                            <div class="col-md-6">
                                <input type="text"  valur="0" class="form-control" id="input-add-tax-minimum" name="tax-minimum" data-mask="({prefix: '<?= $this->translate('corrency_symbol')?> ',clearIncomplete: true,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})">                                    
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-optional" for="input-add-tax-optional"><?= $this->translate('Optional') ?>? </label>
                            <div class="col-md-6">
                                <input type="checkbox" class="form-control" id="input-add-tax-optional" name="tax-optional" value="true">                                    
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">                                
                                <button data-table-row-fields="tax-name,price,minimum-price,optional," data-table-field="[data-table='fixed-tax']" data-add="/<?= $this->module_name ?>/add-fixed-tax.json" name="add-fixed-tax" type="submit" class="btn btn-success pull-right">
                                    <?= ucfirst($this->translate('Add fixed tax')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>