<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add area')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form class="api-form form-horizontal" data-clone-field="[data-clone=add-area]" data-clone-target="#form-area" action="/<?= $this->module_name ?>/add-area.json<?= $this->companyModel->getCurrentPeopleCompany() ? '?company_id=' . $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>" method="POST" name="form-add-area" role="form" >
                        <!-- Form Name -->                        
                        <input name="method" value="POST" type="hidden">
                        <div class="form-group">
                            <label class="control-label col-md-3" id="label-add-state" for="input-add-area"><?= $this->translate('State') ?>: </label>
                            <div class="col-md-3">
                                <select class="form-control" id="input-add-state" name="state" data-list="state">
                                    <?php foreach ($this->states AS $state) { ?>
                                        <option value="<?= $state->getId() ?>"><?= $state->getUf() ?></option>
                                    <?php } ?>
                                </select>
                            </div>                
                            <label class="col-md-2 control-label" id="label-add-city" for="input-add-area"><?= $this->translate('City') ?>: </label>
                            <div class="col-md-4">
                                <select class="form-control" id="input-add-citye" name="city" data-list="city">
                                    <?php foreach ($this->cities AS $city) { ?>
                                        <option value="<?= $city->getId() ?>"><?= $city->getCity() ?></option>
                                    <?php } ?>
                                </select>
                            </div>                                                                                  
                        </div>
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">                                
                                <button data-clone-field="[data-clone=add-area]" data-clone-target="#form-area" data-add="/<?= $this->module_name ?>/add-area.json<?= $this->companyModel->getCurrentPeopleCompany() ? '?company_id=' . $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>" name="add-area" type="submit" class="btn btn-success pull-right">                                        
                                    <?= ucfirst($this->translate('Add area')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>