<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add restriction material')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form class="api-form form-horizontal" data-clone-field="[data-clone=add-restriction-material]" data-clone-target="[data-table-body='restriction-material']" action="/<?= $this->module_name ?>/add-restriction-material.json" method="POST" name="form-add-restriction-material" role="form" >
                        <!-- Form Name -->
                        <input type="hidden" name="company_id" value="<?= $this->companyModel->getCurrentPeopleCompany() ? $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>">
                        <input name="method" value="POST" type="hidden">
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-restriction-type" for="input-add-restriction-type"><?= $this->translate('Restriction type') ?>: </label>
                            <div class="col-md-6">
                                <select class="form-control" id="input-add-restriction-type" name="restriction-type">                                    
                                    <option value="delivery_denied"><?= $this->translate('delivery_denied') ?></option>
                                    <option value="delivery_restricted"><?= $this->translate('delivery_restricted') ?></option>
                                </select>
                            </div>                                            
                        </div>   
                        <div class="form-group">
                            <label class="control-label col-md-6" id="input-add-restriction-material" for="input-add-restriction-material"><?= $this->translate('Material') ?>: </label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="input-add-restriction-material" name="restriction-material"></textarea>
                            </div>                                            
                        </div>   
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">                                
                                <button data-table-row-fields="product-material,restriction-type," data-table-field="[data-table='restriction-material']" data-add="/<?= $this->module_name ?>/add-restriction-material.json" name="add-restriction-material" type="submit" class="btn btn-success pull-right">
                                    <?= ucfirst($this->translate('Add restriction material')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>