<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add tax by region')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form class="api-form form-horizontal" data-clone-field="[data-clone=add-percentage-tax-by-region]" data-clone-target="[data-table-body='percentage-tax-by-region']" action="/<?= $this->module_name ?>/add-percentage-tax-per-region.json" method="POST" name="form-add-percentage-tax-by-region" role="form" >
                        <!-- Form Name -->                        
                        <input type="hidden" name="company_id" value="<?= $this->companyModel->getCurrentPeopleCompany() ? $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>">
                        <input name="method" value="POST" type="hidden">
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-percentage-tax-by-region" for="input-add-percentage-tax-by-region"><?= $this->translate('Tax Name') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-percentage-tax-by-region" name="percentage-tax-by-region" value="<?= $this->percentageTaxByRegion ? $this->percentageTaxByRegion[0]->getTaxName() : '' ?>" required>                                    
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-region-origin" for="input-region-origin"><?= $this->translate('Region origin') ?>: </label>
                            <div class="col-md-6">
                                <select class="form-control" id="input-region-origin" name="region-origin">
                                    <?php foreach ($this->delivery_region AS $region) { ?>
                                        <option value="<?= $region->getId() ?>" <?= $this->percentageTaxByRegion ? $this->percentageTaxByRegion[0]->getRegionOrigin()->getId() === $region->getId() ? 'SELECTED' : '' : '' ?>><?= $region->getRegion() ?></option>
                                    <?php } ?>
                                </select>
                            </div>                                            
                        </div>        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-region-origin" for="input-region-destination"><?= $this->translate('Region destination') ?>: </label>
                            <div class="col-md-6">
                                <select class="form-control" id="input-region-destination" name="region-destination">
                                    <?php foreach ($this->delivery_region AS $region) { ?>
                                        <option value="<?= $region->getId() ?>"><?= $region->getRegion() ?></option>
                                    <?php } ?>
                                </select>
                            </div>                                            
                        </div>        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-final-weight" for="final-weight"><?= $this->translate('Final Weight') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="final-weight" name="final-weight" data-mask="({prefix: '',suffix: ' kg',integerDigits: 7,digits: 3,clearIncomplete: true,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})" required>
                            </div>                                            
                        </div>        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-price" for="input-add-tax-price"><?= $this->translate('Percentage') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-tax-price" name="tax-price" data-mask="({prefix: '',suffix: '%',integerDigits: 3,digits: 2,clearIncomplete: true,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})" required>
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-price" for="input-add-tax-subtype"><?= $this->translate('Percentage Type') ?>: </label>
                            <div class="col-md-6">                                
                                <input type="radio" class="radio-inline" id="input-add-tax-subtype" name="tax-subtype" value="invoice"> <?= $this->translate('Invoice') ?>
                                <input type="radio" class="radio-inline" id="input-add-tax-subtype" name="tax-subtype" value="order"> <?= $this->translate('Freight') ?>
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-minimum" for="input-add-tax-minimum"><?= $this->translate('Minimum Tax') ?>: </label>
                            <div class="col-md-6">
                                <input type="text"  valur="0" class="form-control" id="input-add-tax-minimum" name="tax-minimum" data-mask="({prefix: '<?= $this->translate('corrency_symbol') ?> ',clearIncomplete: true,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})">
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-optional" for="input-add-tax-optional"><?= $this->translate('Optional') ?>? </label>
                            <div class="col-md-6">
                                <input type="checkbox" class="form-control" id="input-add-tax-optional" name="tax-optional" value="true">                                    
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">                                
                                <button data-table-row-fields="tax-name,region_origin,region_destination,final-weight,price,tax-subtype,minimum-price,optional,deadline," data-table-field="[data-table='percentage-tax-by-region']" data-add="/<?= $this->module_name ?>/add-percentage-tax-per-region.json" name="add-percentage-tax-by-region" type="submit" class="btn btn-success pull-right">
                                    <?= ucfirst($this->translate('Add tax by region')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>