<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add tax by weight')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form class="api-form form-horizontal" data-clone-field="[data-clone=add-tax-by-weight]" data-clone-target="[data-table-body='tax-by-weight']" action="/<?= $this->module_name ?>/add-tax-by-weight.json" method="POST" name="form-add-tax-by-weight" role="form" >
                        <!-- Form Name -->                        
                        <input type="hidden" name="company_id" value="<?= $this->companyModel->getCurrentPeopleCompany() ? $this->companyModel->getCurrentPeopleCompany()->getId() : '' ?>">
                        <input name="method" value="POST" type="hidden">
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-by-weight" for="input-add-tax-by-weight"><?= $this->translate('Tax Name') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-tax-by-weight" name="tax-by-weight" required>                                    
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-final-weight" for="final-weight"><?= $this->translate('Final Weight') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="final-weight" name="final-weight" data-mask="({prefix: '',suffix: ' kg',integerDigits: 7,digits: 3,clearIncomplete: true,alias: 'currency',rightAlign: false,radixPoint: ',',groupSeparator: '.'})" required>
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-price" for="input-add-tax-price"><?= $this->translate('Price') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-tax-price" name="tax-price" data-mask="({prefix: '<?= $this->translate('corrency_symbol')?> ',clearIncomplete: true,alias: 'currency',digits: 3,rightAlign: false,radixPoint: ',',groupSeparator: '.'})" required>
                            </div>                                            
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-minimum" for="input-add-tax-minimum"><?= $this->translate('Fraction by weight') ?>: </label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="input-add-tax-minimum" name="tax-minimum" value="1" required>                                    
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <label class="control-label col-md-6" id="label-add-tax-optional" for="input-add-tax-optional"><?= $this->translate('Optional') ?>? </label>
                            <div class="col-md-6">
                                <input type="checkbox" class="form-control" id="input-add-tax-optional" name="tax-optional" value="true">                                    
                            </div>                                            
                        </div>                        
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">                                
                                <button data-table-row-fields="tax-name,final-weight,price,minimum-price,optional," data-table-field="[data-table='tax-by-weight']" data-add="/<?= $this->module_name ?>/add-tax-by-weight.json" name="add-tax-by-weight" type="submit" class="btn btn-success pull-right">
                                    <?= ucfirst($this->translate('Add tax by weight')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>