<div role="tabpanel" class="tab-pane" id="shipping-table">
    <?= $this->partial('tables/fixed-tax.phtml'); ?>
    <?= $this->partial('tables/percentage-tax.phtml'); ?>
    <?= $this->partial('tables/fixed-tax-by-weight.phtml'); ?>
    <?= $this->partial('tables/fixed-tax-by-region.phtml'); ?>
    <?= $this->partial('tables/percentage-tax-by-region.phtml'); ?>
    <?= $this->partial('tables/weight-tax-by-region.phtml'); ?>
</div>